# Generated by Django 6.0.7 on 2026-07-20 15:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trip_type', models.CharField(choices=[('GROUP', 'Group Trip'), ('PRIVATE', 'Private Trip'), ('CUSTOM', 'Custom Trip')], default='GROUP', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_seats', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_seats', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('includes_airport_pickup', models.BooleanField(default=True)),
                ('pickup_location', models.CharField(default='KIA Airport, Arusha', max_length=200)),
                ('includes_accommodation', models.BooleanField(default=True)),
                ('includes_meals', models.BooleanField(default=True)),
                ('includes_transport', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trips/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_full', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinations', models.ManyToManyField(related_name='trips', to='tours_app.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_type', models.CharField(choices=[('LOCAL', 'Local (Tanzanian)'), ('INTERNATIONAL', 'International')], default='INTERNATIONAL', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('number_of_seats', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('special_requests', models.TextField(blank=True)),
                ('needs_airport_pickup', models.BooleanField(default=False)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours_app.trip')),
            ],
        ),
    ]
