# Generated by Django 6.0.7 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_video_url', models.URLField(default='https://videos.pexels.com/video-files/5388365/5388365-hd_1920_1080_25fps.mp4', help_text='Direct MP4 URL used behind the homepage heading.')),
                ('hero_poster_url', models.URLField(default='https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=85', help_text='Fallback image shown while the video loads or when video is unavailable.')),
                ('hero_badge', models.CharField(default='Tanzania safari journeys', max_length=100)),
            ],
            options={
                'verbose_name': 'Site appearance',
                'verbose_name_plural': 'Site appearance',
            },
        ),
    ]
