# Generated by Django 6.0.7 on 2026-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0002_siteappearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_point',
            field=models.CharField(blank=True, choices=[('KIA Airport - KIA', 'Kilimanjaro International Airport - KIA'), ('Arusha Town/Central Hotels', 'Arusha Town/Central Hotels'), ('Arusha City/Clocktower', 'Arusha City/Clocktower')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='international_pickup',
            field=models.CharField(default='Kilimanjaro International Airport - KIA', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='local_pickup',
            field=models.CharField(default='Arusha Town/Central Hotels', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
