# Generated by Django 6.0.7 on 2026-07-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0003_booking_pickup_point_trip_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_remote_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='image_remote_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
