# Generated by Django 6.0.7 on 2026-07-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0004_destination_image_remote_url_trip_image_remote_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteappearance',
            name='hero_poster_url',
            field=models.URLField(blank=True, help_text='Fallback image shown while the video loads or when video is unavailable. Leave empty to use the sample poster.'),
        ),
        migrations.AlterField(
            model_name='siteappearance',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='Direct MP4 URL used behind the homepage heading. Leave empty to use the sample safari video.'),
        ),
    ]
